import { MealTemplate } from '../types';

export const MEAL_TEMPLATES: MealTemplate[] = [
  // ─── Breakfast ──────────────────────────────────────────────────────────────
  {
    id: 'egg_tomato',
    name: 'Scrambled Eggs with Tomato',
    meal_type: 'breakfast',
    required_ingredients: ['eggs', 'tomato'],
    optional_ingredients: ['olive oil', 'salt', 'pepper'],
    estimated_calories: 280,
    carb_level: 'low',
    allergens: ['eggs'],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'fruit_protein',
    name: 'Fruit & Protein Plate',
    meal_type: 'breakfast',
    required_ingredients: ['fruit'],
    optional_ingredients: ['Greek yogurt', 'nuts'],
    estimated_calories: 300,
    carb_level: 'moderate',
    allergens: ['dairy'],
    phase_suitable: ['restart', 'build', 'sharpen'],
  },
  {
    id: 'meat_tomato_breakfast',
    name: 'Leftover Meat & Tomato',
    meal_type: 'breakfast',
    required_ingredients: ['meat', 'tomato'],
    optional_ingredients: ['olive oil', 'salt'],
    estimated_calories: 320,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'rice_cake_protein',
    name: 'Rice Cake with Meat',
    meal_type: 'breakfast',
    required_ingredients: ['rice cake', 'meat'],
    optional_ingredients: ['tomato'],
    estimated_calories: 350,
    carb_level: 'moderate',
    allergens: [],
    phase_suitable: ['restart', 'build'],
  },
  {
    id: 'oats_fruit',
    name: 'Oatmeal with Fruit',
    meal_type: 'breakfast',
    required_ingredients: ['oats', 'fruit'],
    optional_ingredients: ['honey', 'milk'],
    estimated_calories: 380,
    carb_level: 'high',
    allergens: ['dairy'],
    phase_suitable: ['restart', 'build'],
  },

  // ─── Lunch ──────────────────────────────────────────────────────────────────
  {
    id: 'chicken_rice_broccoli',
    name: 'Chicken Rice Bowl',
    meal_type: 'lunch',
    required_ingredients: ['chicken breast', 'rice'],
    optional_ingredients: ['broccoli', 'cabbage', 'soy sauce'],
    estimated_calories: 480,
    carb_level: 'moderate',
    allergens: ['soy'],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'meat_veggie_rice',
    name: 'Meat & Vegetable Rice Plate',
    meal_type: 'lunch',
    required_ingredients: ['meat', 'rice'],
    optional_ingredients: ['broccoli', 'cabbage', 'tomato'],
    estimated_calories: 500,
    carb_level: 'moderate',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'grilled_meat_salad',
    name: 'Grilled Meat & Cabbage Salad',
    meal_type: 'lunch',
    required_ingredients: ['meat', 'cabbage'],
    optional_ingredients: ['tomato', 'olive oil', 'lemon'],
    estimated_calories: 380,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['sharpen', 'competition_ready'],
  },
  {
    id: 'tuna_rice',
    name: 'Tuna Rice Bowl',
    meal_type: 'lunch',
    required_ingredients: ['tuna', 'rice'],
    optional_ingredients: ['tomato', 'cucumber', 'soy sauce'],
    estimated_calories: 420,
    carb_level: 'moderate',
    allergens: ['fish', 'soy'],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'broccoli_chicken_lowcarb',
    name: 'Chicken & Broccoli Bowl (Low Carb)',
    meal_type: 'lunch',
    required_ingredients: ['chicken breast', 'broccoli'],
    optional_ingredients: ['garlic', 'olive oil', 'salt'],
    estimated_calories: 320,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['sharpen', 'competition_ready'],
  },
  {
    id: 'egg_rice_bowl',
    name: 'Egg & Rice Bowl',
    meal_type: 'lunch',
    required_ingredients: ['eggs', 'rice'],
    optional_ingredients: ['tomato', 'soy sauce', 'sesame oil'],
    estimated_calories: 420,
    carb_level: 'high',
    allergens: ['eggs', 'soy'],
    phase_suitable: ['restart', 'build'],
  },

  // ─── Dinner ─────────────────────────────────────────────────────────────────
  {
    id: 'meat_veg_dinner',
    name: 'Grilled Meat & Steamed Vegetables',
    meal_type: 'dinner',
    required_ingredients: ['meat'],
    optional_ingredients: ['broccoli', 'cabbage', 'tomato', 'olive oil'],
    estimated_calories: 420,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'meat_rice_cake_dinner',
    name: 'Meat & Rice Cake Dinner',
    meal_type: 'dinner',
    required_ingredients: ['meat', 'rice cake'],
    optional_ingredients: ['broccoli', 'tomato'],
    estimated_calories: 480,
    carb_level: 'moderate',
    allergens: [],
    phase_suitable: ['restart', 'build'],
  },
  {
    id: 'beef_broccoli_dinner',
    name: 'Beef & Broccoli',
    meal_type: 'dinner',
    required_ingredients: ['beef', 'broccoli'],
    optional_ingredients: ['garlic', 'soy sauce', 'olive oil'],
    estimated_calories: 440,
    carb_level: 'low',
    allergens: ['soy'],
    phase_suitable: ['sharpen', 'competition_ready'],
  },
  {
    id: 'cabbage_meat_soup',
    name: 'Meat & Cabbage Soup',
    meal_type: 'dinner',
    required_ingredients: ['meat', 'cabbage'],
    optional_ingredients: ['tomato', 'garlic', 'salt', 'pepper'],
    estimated_calories: 350,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'rice_veggie_dinner',
    name: 'Rice & Vegetable Bowl (Training Day)',
    meal_type: 'dinner',
    required_ingredients: ['rice'],
    optional_ingredients: ['broccoli', 'cabbage', 'tomato', 'sesame oil'],
    estimated_calories: 380,
    carb_level: 'high',
    allergens: [],
    phase_suitable: ['restart', 'build'],
  },

  // ─── Snacks ─────────────────────────────────────────────────────────────────
  {
    id: 'fruit_snack',
    name: 'Fresh Fruit',
    meal_type: 'snack',
    required_ingredients: ['fruit'],
    optional_ingredients: [],
    estimated_calories: 120,
    carb_level: 'moderate',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'tomato_snack',
    name: 'Cherry Tomatoes',
    meal_type: 'snack',
    required_ingredients: ['tomato'],
    optional_ingredients: ['salt'],
    estimated_calories: 50,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
  {
    id: 'rice_cake_snack',
    name: 'Rice Cake (Plain)',
    meal_type: 'snack',
    required_ingredients: ['rice cake'],
    optional_ingredients: [],
    estimated_calories: 100,
    carb_level: 'moderate',
    allergens: [],
    phase_suitable: ['restart', 'build'],
  },
  {
    id: 'meat_snack',
    name: 'Protein Snack (Leftover Meat)',
    meal_type: 'snack',
    required_ingredients: ['meat'],
    optional_ingredients: [],
    estimated_calories: 150,
    carb_level: 'low',
    allergens: [],
    phase_suitable: ['sharpen', 'competition_ready'],
  },
  {
    id: 'egg_snack',
    name: 'Hard-Boiled Egg',
    meal_type: 'snack',
    required_ingredients: ['eggs'],
    optional_ingredients: ['salt'],
    estimated_calories: 140,
    carb_level: 'low',
    allergens: ['eggs'],
    phase_suitable: ['restart', 'build', 'sharpen', 'competition_ready'],
  },
];
